-- 코드를 입력하세요
# SELECT ANIMAL_ID, NAME
# FROM ANIMAL_OUTS
# WHERE ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAL_INS);

SELECT A.ANIMAL_ID, A.NAME
FROM ANIMAL_OUTS A
LEFT JOIN ANIMAL_INS B USING(ANIMAL_ID)
WHERE A.NAME IS NOT NULL AND B.NAME IS NULL;