-- 코드를 입력하세요
SELECT B.FOOD_TYPE, B.REST_ID, B.REST_NAME, B.FAVORITES
FROM REST_INFO B, (SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES FROM REST_INFO GROUP BY FOOD_TYPE) A
WHERE B.FOOD_TYPE = A.FOOD_TYPE AND B.FAVORITES = A.FAVORITES 
ORDER BY B.FOOD_TYPE DESC;