-- 코드를 입력하세요
SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES*PRICE) AS TOTAL_SALES
FROM BOOK
JOIN AUTHOR USING(AUTHOR_ID)
JOIN BOOK_SALES 
ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID AND YEAR(SALES_DATE) = '2022' AND MONTH(SALES_DATE) = '01'
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC;

# SELECT * FROM BOOK JOIN AUTHOR USING(AUTHOR_ID) JOIN BOOK_SALES 
# ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID AND YEAR(SALES_DATE) = '2022' AND MONTH(SALES_DATE) = '01';

# 2022년 1월 판매 도서
# 저자별, 카테고리 별
# 매출액
# 정렬